### ISSUE TITLE
侧滑删除程序崩溃

### ISSUE THREAD

**Issue by liuqingdada** [yin450561200/SwipeRecyclerView#1]
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.liuqing.app.launcher, PID: 10999
                                                   java.lang.ArrayIndexOutOfBoundsException: length=13; index=-1
                                                       at android.support.v4.util.SparseArrayCompat.keyAt(SparseArrayCompat.java:240)
                                                       at com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper.getItemViewType(SwipeAdapterWrapper.java:88)
                                                       at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.drawHorizontal(DefaultItemDecoration.java:164)
                                                       at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.onDraw(DefaultItemDecoration.java:154)
                                                       at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3934)
                                                       at android.view.View.draw(View.java:15231)
                                                       at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
                                                       at android.view.View.draw(View.java:15140)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                       at android.view.View.draw(View.java:15234)
                                                       at com.liuqing.app.launcher.customview.viewpager.VerticalViewPager.draw(VerticalViewPager.java:2093)
                                                       at android.view.View.draw(View.java:15140)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                       at android.view.View.draw(View.java:15234)
                                                       at android.support.v4.view.ViewPager.draw(ViewPager.java:2443)
                                                       at android.view.View.draw(View.java:15140)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                       at android.view.View.draw(View.java:15138)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                       at android.view.View.draw(View.java:15138)
                                                       at android.view.ViewGroup.drawChild(ViewGroup.java:3405)
                                                       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3198)
                                                       at android.view.View.draw(View.java:15234)
                                                       at android.widget.FrameLayout.draw(FrameLayout.java:598)
                                                       at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2655)
                                                       at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:2644)
                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2557)
                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2352)
                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1982)
                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                       at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                       at android.os.Handler.handleCallback(Handler.java:739)
                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                       at android.os.Looper.loop(Looper.java:135)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:955)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:750)

关键位置：SwipeAdapterWrapper.java:88
public int getItemViewType(int position) {
        if (isHeaderView(position)) {
            return mHeaderViews.keyAt(position);    // 88行
        } else if (isFooterView(position)) {
            return mFootViews.keyAt(position - getHeaderItemCount() - getContentItemCount());
        }
        return mAdapter.getItemViewType(position - getHeaderItemCount());
    }

**Comment by liuqingdada** [comment]
demo也有这个错误：
E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                          Process: com.yanzhenjie.recyclerview.swipe.sample, PID: 14822
                                                                                          java.lang.ArrayIndexOutOfBoundsException: length=13; index=-1
                                                                                              at android.support.v4.util.SparseArrayCompat.keyAt(SparseArrayCompat.java:240)
                                                                                              at com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper.getItemViewType(SwipeAdapterWrapper.java:88)
                                                                                              at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.drawHorizontal(DefaultItemDecoration.java:164)
                                                                                              at com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.onDraw(DefaultItemDecoration.java:154)
                                                                                              at android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3934)
                                                                                              at android.view.View.draw(View.java:15158)
                                                                                              at android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
